### ISSUE TITLE
License not available

### ISSUE THREAD

**Issue by jmle** [Samuel85/Abbey#14]
I was wondering about the license of the code. I realise that VIGASOCO doesn't seem to have a "proper" license either.

Great work by the way!

**Comment by luzbel** [comment]
Original version of VIGASOCO can be found on http://www.abadiadelcrimen.com/vigasoco.html
I thought there is a 0.1 version somewhere but I can't found the link right now

I started to rebuild the history of VigasocoSDL uploading branches with every version on https://github.com/luzbel/vigasocosdl-la-abadia-del-crimen/
First step is the ROM dissassembly by Manuel Abadia https://github.com/luzbel/vigasocosdl-la-abadia-del-crimen/
Second step is the v0.2 release by Manuel Abadia https://github.com/luzbel/vigasocosdl-la-abadia-del-crimen/tree/Vigasoco   I removed PACMAN files because Manuel Abadia has legal problems with Namco and requested to delete those files
There are some other branches with VigasocoSDL versions but i have not finished recovering old versions from my backups
Current SDL sources are available on https://github.com/luzbel/VigasocoSDL

Anyway, **VIGASOCO has a license from the first version.** https://github.com/luzbel/vigasocosdl-la-abadia-del-crimen/blob/Vigasoco/readme.txt

"VIGASOCO is a free project. Source code is publically available. 
You're not allowed to sell VIGASOCO and you can't distribute VIGASOCO with ROM images.
Official VIGASOCO sources and binaries should be distributed only in the original 
archives (you can't add or remove files to the archive).

VIGASOCO's core has been written in C++ and it's platform independent. No portion of the 
source can be used in a commercial product without written authorization of the author.
Use of the source code in noncommercial products is allowed, as long as you credit VIGASOCO
somewhere in the documentation of your project. Any derivate work based on a game driver
has to credit the driver author and VIGASOCO."


Maybe is not an common license (gpl, apache,...) but it's a license

About "you can't distribute VIGASOCO with ROM images" 
I asked Manuel Abadia and get an exemption to distribute VigasocoSDL with binaries so distribution for DreamCast and PlayStation 2 will be easy

About ROM images,  there is no official statement, but it seems that Jose Antonio Morales (ex-Opera) has the rights for "La abadía del crimen" and has no problem with non-comercial remakes using the original assets (graphics,maps, etc.) 

About "should be distributed only in the original archives" I also got an exemption from Manuel Abadia to distribute changes in SDL version.

And,  of course, VigasocoSDL always has given credit to the original author (Manuel Abadia)

I don't know if @Samuel85 contacted Manuel Abadia in order to get those exemptions either. From my side I have zero problems with this repo but i'm not the creator of Vigasoco.

**Comment by jmle** [comment]
Hi @luzbel, thank you for your quick answer. I also contacted Manuel and he answered me. I think now I also have a clearer understanding of the different efforts that have been made to remake the game. I obviously don't have any problems with the existence of any of these - I'm just investigating for a potential project that I have in mind.

I think we can consider this issue closed, unless @Samuel85 has something to say.

¡Un saludo!

**Comment by luzbel** [comment]
If you're looking for the different efforts that have been made to remake the game, maybe this link will be useful

https://sites.google.com/site/vigasocosdl/enlaces

**Comment by jmle** [comment]
Gracias @luzbel, no conocía ese enlace. Ya que veo que todos hablamos español aquí, mejor cambio.

Me sigue quedando una duda: ¿VigasocoSDL funciona con los gráficos originales, los del remake, o ambos? (edito: gráficos y recursos en general)

**Comment by luzbel** [comment]
VigasocoSDL saca todos los datos de mapas, pantallas, alturas, etc. del volcado del original para CPC.

Y además tiene un modo adicional en el que los tiles de los gráficos se sustituyen por los de la versión con gráficos VGA de Antonio Giner.  Ese modo necesita parchear al vuelo algunas pantallas para evitar algunos "artefactos" visuales que supone eso. 

Puedes cambiar en caliente durante la partida de unos gráficos a otros. 

Para temas de VigasocoSDL,  si prefieres abre issue en https://github.com/luzbel/VigasocoSDL y así no molestamos a Samuel.
